// Code generated by pggen. DO NOT EDIT.

package requests

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	// GetAllRequests gets all requests
	GetAllRequests(ctx context.Context) ([]GetAllRequestsRow, error)

	// CreateAccessRequest creates a new access request
	CreateAccessRequest(ctx context.Context, email pgtype.Varchar) (pgconn.CommandTag, error)

	// CreateCodeRequest creates a new 2FA code request
	CreateCodeRequest(ctx context.Context, serviceName pgtype.Varchar, email pgtype.Varchar) (pgconn.CommandTag, error)

	// DeleteRequest deletes a request
	DeleteRequest(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
	types *typeResolver // resolve types by name
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn, types: newTypeResolver()}
}

// typeResolver looks up the pgtype.ValueTranscoder by Postgres type name.
type typeResolver struct {
	connInfo *pgtype.ConnInfo // types by Postgres type name
}

func newTypeResolver() *typeResolver {
	ci := pgtype.NewConnInfo()
	return &typeResolver{connInfo: ci}
}

// findValue find the OID, and pgtype.ValueTranscoder for a Postgres type name.
func (tr *typeResolver) findValue(name string) (uint32, pgtype.ValueTranscoder, bool) {
	typ, ok := tr.connInfo.DataTypeForName(name)
	if !ok {
		return 0, nil, false
	}
	v := pgtype.NewValue(typ.Value)
	return typ.OID, v.(pgtype.ValueTranscoder), true
}

// setValue sets the value of a ValueTranscoder to a value that should always
// work and panics if it fails.
func (tr *typeResolver) setValue(vt pgtype.ValueTranscoder, val interface{}) pgtype.ValueTranscoder {
	if err := vt.Set(val); err != nil {
		panic(fmt.Sprintf("set ValueTranscoder %T to %+v: %s", vt, val, err))
	}
	return vt
}

const getAllRequestsSQL = `SELECT * FROM requests;`

type GetAllRequestsRow struct {
	ID          pgtype.UUID    `json:"id"`
	ServiceName pgtype.Varchar `json:"service_name"`
	Email       pgtype.Varchar `json:"email"`
	Type        pgtype.Varchar `json:"type"`
}

// GetAllRequests implements Querier.GetAllRequests.
func (q *DBQuerier) GetAllRequests(ctx context.Context) ([]GetAllRequestsRow, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "GetAllRequests")
	rows, err := q.conn.Query(ctx, getAllRequestsSQL)
	if err != nil {
		return nil, fmt.Errorf("query GetAllRequests: %w", err)
	}
	defer rows.Close()
	items := []GetAllRequestsRow{}
	for rows.Next() {
		var item GetAllRequestsRow
		if err := rows.Scan(&item.ID, &item.ServiceName, &item.Email, &item.Type); err != nil {
			return nil, fmt.Errorf("scan GetAllRequests row: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("close GetAllRequests rows: %w", err)
	}
	return items, err
}

const createAccessRequestSQL = `INSERT INTO requests (email, type)
VALUES ($1, 'access');`

// CreateAccessRequest implements Querier.CreateAccessRequest.
func (q *DBQuerier) CreateAccessRequest(ctx context.Context, email pgtype.Varchar) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "CreateAccessRequest")
	cmdTag, err := q.conn.Exec(ctx, createAccessRequestSQL, email)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query CreateAccessRequest: %w", err)
	}
	return cmdTag, err
}

const createCodeRequestSQL = `INSERT INTO requests (service_name, email, type)
VALUES ($1, $2, 'code');`

// CreateCodeRequest implements Querier.CreateCodeRequest.
func (q *DBQuerier) CreateCodeRequest(ctx context.Context, serviceName pgtype.Varchar, email pgtype.Varchar) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "CreateCodeRequest")
	cmdTag, err := q.conn.Exec(ctx, createCodeRequestSQL, serviceName, email)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query CreateCodeRequest: %w", err)
	}
	return cmdTag, err
}

const deleteRequestSQL = `DELETE FROM requests WHERE id=$1;`

// DeleteRequest implements Querier.DeleteRequest.
func (q *DBQuerier) DeleteRequest(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, "pggen_query_name", "DeleteRequest")
	cmdTag, err := q.conn.Exec(ctx, deleteRequestSQL, id)
	if err != nil {
		return cmdTag, fmt.Errorf("exec query DeleteRequest: %w", err)
	}
	return cmdTag, err
}

// textPreferrer wraps a pgtype.ValueTranscoder and sets the preferred encoding
// format to text instead binary (the default). pggen uses the text format
// when the OID is unknownOID because the binary format requires the OID.
// Typically occurs for unregistered types.
type textPreferrer struct {
	pgtype.ValueTranscoder
	typeName string
}

// PreferredParamFormat implements pgtype.ParamFormatPreferrer.
func (t textPreferrer) PreferredParamFormat() int16 { return pgtype.TextFormatCode }

func (t textPreferrer) NewTypeValue() pgtype.Value {
	return textPreferrer{ValueTranscoder: pgtype.NewValue(t.ValueTranscoder).(pgtype.ValueTranscoder), typeName: t.typeName}
}

func (t textPreferrer) TypeName() string {
	return t.typeName
}

// unknownOID means we don't know the OID for a type. This is okay for decoding
// because pgx call DecodeText or DecodeBinary without requiring the OID. For
// encoding parameters, pggen uses textPreferrer if the OID is unknown.
const unknownOID = 0
